language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U -r requirements.user.txt
  - pip install pylint
script: pylint -f colorized app/*.py
