FROM resin/%%RESIN_MACHINE_NAME%%-python:3

RUN apt-get update && apt-get install -yq \
    mc sudo libpcap-dev git vim && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN export GIT_SSL_NO_VERIFY=1 && \
    git config --global http.sslVerify false

ADD app/ /usr/src/app/

ENV INITSYSTEM on

VOLUME /usr/src/app

CMD cd /root/dasher && cp -n config.json /root/dasher/config/config.json && npm run start
